"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-30 18:46:31.381768
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64, collation="NOCASE"), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("disabled_at", sa.DateTime(), nullable=True),
        sa.Column("prefs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=255), nullable=False),
        sa.Column("result_path", sa.String(length=1024), nullable=True),
        sa.Column("result_size", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_jobs_owner_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("trashed_at", sa.DateTime(), nullable=True),
        sa.Column("trash_root_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind IN ('folder', 'notebook', 'bookmark')", name=op.f("ck_nodes_kind")),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 255", name=op.f("ck_nodes_name_length")),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_nodes_owner_id_users"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["nodes.id"], name=op.f("fk_nodes_parent_id_nodes"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_nodes_live_children",
            ["owner_id", "parent_id"],
            unique=False,
            sqlite_where=sa.text("trashed_at IS NULL"),
        )
        batch_op.create_index(batch_op.f("ix_nodes_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index("ix_nodes_trash_root", ["owner_id", "trash_root_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("orphaned_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_sources_owner_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("owner_id", "sha256", name=op.f("uq_sources_owner_id_sha256")),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_orphaned_at"), ["orphaned_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "notebooks",
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], name=op.f("fk_notebooks_node_id_nodes"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("node_id", name=op.f("pk_notebooks")),
    )
    op.create_table(
        "reading_progress",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("page_id", sa.String(length=36), nullable=True),
        sa.Column("page_index", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"], ["nodes.id"], name=op.f("fk_reading_progress_node_id_nodes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reading_progress_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "node_id", name=op.f("pk_reading_progress")),
    )
    op.create_table(
        "source_pages",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("width_pt", sa.Float(), nullable=False),
        sa.Column("height_pt", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_source_pages_source_id_sources"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("source_id", "idx", name=op.f("pk_source_pages")),
    )
    op.create_table(
        "bookmarks",
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("notebook_id", sa.String(length=36), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], name=op.f("fk_bookmarks_node_id_nodes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["notebook_id"], ["notebooks.node_id"], name=op.f("fk_bookmarks_notebook_id_notebooks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("node_id", name=op.f("pk_bookmarks")),
    )
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bookmarks_notebook_id"), ["notebook_id"], unique=False)

    op.create_table(
        "pages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("notebook_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("source_index", sa.Integer(), nullable=False),
        sa.Column("rotation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_batch", sa.String(length=36), nullable=True),
        sa.Column("deleted_position", sa.Integer(), nullable=True),
        sa.CheckConstraint("rotation IN (0, 90, 180, 270)", name=op.f("ck_pages_rotation")),
        sa.ForeignKeyConstraint(
            ["notebook_id"], ["notebooks.node_id"], name=op.f("fk_pages_notebook_id_notebooks"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_pages_source_id_sources"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("id", "notebook_id", name=op.f("uq_pages_id_notebook_id")),
        sa.UniqueConstraint("notebook_id", "position", name=op.f("uq_pages_notebook_id_position")),
    )
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_pages_deleted", ["deleted_at"], unique=False, sqlite_where=sa.text("deleted_at IS NOT NULL")
        )
        batch_op.create_index(batch_op.f("ix_pages_deleted_batch"), ["deleted_batch"], unique=False)
        batch_op.create_index(batch_op.f("ix_pages_source_id"), ["source_id"], unique=False)

    op.create_table(
        "bookmark_pages",
        sa.Column("bookmark_id", sa.String(length=36), nullable=False),
        sa.Column("page_id", sa.String(length=36), nullable=False),
        sa.Column("notebook_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["bookmark_id"],
            ["bookmarks.node_id"],
            name=op.f("fk_bookmark_pages_bookmark_id_bookmarks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["page_id", "notebook_id"],
            ["pages.id", "pages.notebook_id"],
            name=op.f("fk_bookmark_pages_page_id_notebook_id_pages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bookmark_id", "page_id", name=op.f("pk_bookmark_pages")),
    )
    with op.batch_alter_table("bookmark_pages", schema=None) as batch_op:
        batch_op.create_index("ix_bookmark_pages_page", ["page_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookmark_pages", schema=None) as batch_op:
        batch_op.drop_index("ix_bookmark_pages_page")

    op.drop_table("bookmark_pages")
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pages_source_id"))
        batch_op.drop_index(batch_op.f("ix_pages_deleted_batch"))
        batch_op.drop_index("ix_pages_deleted", sqlite_where=sa.text("deleted_at IS NOT NULL"))

    op.drop_table("pages")
    with op.batch_alter_table("bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bookmarks_notebook_id"))

    op.drop_table("bookmarks")
    op.drop_table("source_pages")
    op.drop_table("reading_progress")
    op.drop_table("notebooks")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_owner_id"))
        batch_op.drop_index(batch_op.f("ix_sources_orphaned_at"))

    op.drop_table("sources")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_index("ix_nodes_trash_root")
        batch_op.drop_index(batch_op.f("ix_nodes_parent_id"))
        batch_op.drop_index("ix_nodes_live_children", sqlite_where=sa.text("trashed_at IS NULL"))

    op.drop_table("nodes")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_owner_id"))

    op.drop_table("jobs")
    op.drop_table("users")
    # ### end Alembic commands ###
