"""pins and page text

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 21:29:26.045578
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_texts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("embedded_text", sa.Text(), nullable=False),
        sa.Column("embedded_done", sa.Boolean(), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=False),
        sa.Column("ocr_engine", sa.String(length=64), nullable=True),
        sa.Column("ocr_rank", sa.Integer(), nullable=True),
        sa.Column("ocr_failed_rank", sa.Integer(), nullable=True),
        sa.Column("ocr_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_page_texts_source_id_sources"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_texts")),
        sa.UniqueConstraint("source_id", "idx", name=op.f("uq_page_texts_source_id_idx")),
    )
    op.create_table(
        "pins",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], name=op.f("fk_pins_node_id_nodes"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_pins_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "node_id", name=op.f("pk_pins")),
    )
    # Full-text index over each page's text (typed + recognised), kept in sync by triggers.
    op.execute("CREATE VIRTUAL TABLE page_text_fts USING fts5(body, tokenize = 'unicode61 remove_diacritics 2')")
    op.execute("CREATE VIRTUAL TABLE page_text_vocab USING fts5vocab(page_text_fts, 'row')")
    op.execute(
        """
        CREATE TRIGGER page_texts_ai AFTER INSERT ON page_texts BEGIN
            INSERT INTO page_text_fts(rowid, body) VALUES (new.id, new.embedded_text || ' ' || new.ocr_text);
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER page_texts_ad AFTER DELETE ON page_texts BEGIN
            DELETE FROM page_text_fts WHERE rowid = old.id;
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER page_texts_au AFTER UPDATE OF embedded_text, ocr_text ON page_texts BEGIN
            DELETE FROM page_text_fts WHERE rowid = old.id;
            INSERT INTO page_text_fts(rowid, body) VALUES (new.id, new.embedded_text || ' ' || new.ocr_text);
        END
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS page_texts_au")
    op.execute("DROP TRIGGER IF EXISTS page_texts_ad")
    op.execute("DROP TRIGGER IF EXISTS page_texts_ai")
    op.execute("DROP TABLE IF EXISTS page_text_vocab")
    op.execute("DROP TABLE IF EXISTS page_text_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pins")
    op.drop_table("page_texts")
    # ### end Alembic commands ###
