"""classes and page tags

Pages can be tagged with a date (``pages.tag_date``) and any number of the user's classes
(``page_classes``). The column is added with a plain ALTER TABLE, so ``pages`` is not
recreated.

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 14:44:37.658605
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80, collation="NOCASE"), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_classes_owner_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("owner_id", "name", name=op.f("uq_classes_owner_id_name")),
    )
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_classes_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "page_classes",
        sa.Column("page_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.id"], name=op.f("fk_page_classes_class_id_classes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], name=op.f("fk_page_classes_page_id_pages"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("page_id", "class_id", name=op.f("pk_page_classes")),
    )
    with op.batch_alter_table("page_classes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_page_classes_class_id"), ["class_id"], unique=False)

    op.add_column("pages", sa.Column("tag_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_column("tag_date")

    with op.batch_alter_table("page_classes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_classes_class_id"))

    op.drop_table("page_classes")
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classes_owner_id"))

    op.drop_table("classes")
    # ### end Alembic commands ###
